/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jni_libconvd_JNIWrapper */

#ifndef _Included_com_github_jni_libconvd_JNIWrapper
#define _Included_com_github_jni_libconvd_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jni_libconvd_JNIWrapper
 * Method:    JNI_convd_lib_version
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_github_jni_libconvd_JNIWrapper_JNI_1convd_1lib_1version
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif